#
# Copyright (c) 2023 Joel Winarske
#

if (APPLE)
    set(CPACK_GENERATOR "Bundle")
elseif (UNIX)
    set(CPACK_GENERATOR "TGZ;RPM;DEB")
elseif(WIN32)
    message(FATAL_ERROR "Not implemented for Windows")
endif()

set(CPACK_BUNDLE_NAME "Luxonis DepthAi-core")
set(CPACK_BUNDLE_PLIST "TODO")
set(CPACK_BUNDLE_ICON "TODO")

if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
    set(CPACK_PACKAGE_NAME ${PROJECT_NAME}-dbg)
else ()
    set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
endif ()

set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Luxonis DepthAI-core - ${CMAKE_BUILD_TYPE}")
set(CPACK_PACKAGE_VENDOR "Luxonis")
set(CPACK_PACKAGE_CONTACT "joel.winarske@gmail.com")

set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
set(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_BINARY_DIR}/_packages")

set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)

set(CPACK_DEB_COMPONENT_INSTALL YES)

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Joel Winarske <joel.winarske@gmail.com>")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)

set(CPACK_RPM_COMPONENT_INSTALL YES)
set(CPACK_RPM_FILE_NAME RPM-DEFAULT)
set(CPACK_RPM_PACKAGE_LICENSE "Apache-2.0")
set(CPACK_RPM_PACKAGE_VENDOR "${CPACK_PACKAGE_VENDOR}")
set(CPACK_RPM_PACKAGE_DESCRIPTION "${CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY}")

set(CPACK_TGZ_FILE_NAME TGZ-DEFAULT)

if (${CMAKE_BUILD_TYPE} STREQUAL "Release")
    set(CPACK_STRIP_FILES homescreen)
endif ()

if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
    set(CPACK_DEBIAN_DEBUGINFO_PACKAGE ON)
    set(CMAKE_RPM_DEBUGINFO_PACKAGE ON)
    set(CMAKE_TGZ_DEBUGINFO_PACKAGE ON)
endif ()

include(CPack)